def Messages():
    m = {'CMDAfterCopy': "Copied %s to the clipboard", 'CMDAfterCut': "Copied %s to the clipboard",
         'CMDAfterPaste': "Pasted %s as %s",
         'CMDAliasNotForUO': "Only unit ops can create alias and %s in not a unit op",
         'CMDAliasNotPort': "Cannot alias %s as it is not a port", 'CMDAmbiguousUnit': "Ambiguous unit %s",
         'CMDBadOperator': "Unknown operator %s", 'CMDBeforePaste': "Pasting %s",
         'CMDCanNotDelete': "Cannot delete object", 'CMDCDInvalidObject': "Cannot cd to object %s",
         'CMDCallBackException': "Call Back Exception %s", 'CMDCannotConnectTo': "Cannot connect to %s",
         'CMDCantUseFileName': "You can not store files named %s",
         'CMDClipboardEmpty': "Clipboard from simulator is empty", 'CMDCompressing': "Compressing file %s",
         'CMDConnectNonPort': "Cannot connect to %s", 'CMDConnectTypeMismatch': "Port type mismatch connecting to %s",
         'CMDCouldNotAssign': "Could not assign %s", 'CMDCouldNotOpenFile': "Could not open file %s",
         'CMDExtracting': "Extracting file %s to %s", 'CMDFailedClone': "Failed while cloning %s",
         'CMDFinishedRecall': "Finished recallling case %s", 'CMDInvalidContents': "Cannot get contents of %s",
         'CMDInvalidObject': "Invalid object %s", 'CMDInvalidUnitSet': "Invalid unit set %s",
         'CMDInvalidNameSyntax': "Invalid name for object '%s'. It can not be a keyword or contain: ' ', ';' or start with: '/', '$'",
         'CMDNoCmpsMismatch': "Incorrect number of component fractions", 'CMDNoSuchName': "There is no object named %s",
         'CMDNotifyAdd': "Add to %s: %s", 'CMDNotifyAddCompound': "Added pure compound to %s: %s",
         'CMDNotifyAddHypo': "Added new hypo compound to %s: %s",
         'CMDNotifyAddObj': "Add object to %s: %s = %s (cmd = %s)", 'CMDNotifyBeforeAdd': "Adding to %s: %s",
         'CMDNotifyBeforeMinus': "Removing from %s: %s", 'CMDNotifyBeforeDeleteObj': "Deleting object from %s: %s",
         'CMDNotifyBeforeDisconnect': "Disconnecting %s from %s", 'CMDNotifyBeforeReadFile': "Processing %s",
         'CMDNotifyClear': "Case cleared", 'CMDNotifyConnect': "Connected %s to %s",
         'CMDNotifyCreateObj': "Created new object in %s: %s (command = %s)",
         'CMDNotifyCreateThermo': "Created new property package %s: %s",
         'CMDNotifyDeleteCompound': "Deleted compound from %s: %s", 'CMDNotifyDeleteObj': "Object deleted from %s: %s",
         'CMDNotifyDisconnect': "Disconnected %s from %s", 'CMDNotifyMinus': "Minus from %s: %s",
         'CMDNotifyMoveCompound': "In %s moved compound %s before %s", 'CMDNotifyReadFile': "Processed %s",
         'CMDNotifySetValue': "Set value %s = %s", 'CMDNotifyStore': "Case stored to file %s ",
         'CMDNotifyUnits': "New active unit set = %s",
         'CMDObsoleteCommand': "The usage of %s is obsolete and will be deprecated. Use %s instead",
         'CMDRecallError': "Error Recalling %s: %s.",
         'CMDThermoConnected': "Thermo case attached to a unit operation. %s to %s",
         'CMDThermoDisconnected': "Thermo case disconnected from unit operation. %s from %s",
         'CMDUnhandledError': "Error processing command:\n%s\n%s\n%s", 'CMDUnknownObject': "Unknown object %s",
         'CMDUnknownUnit': "Unknown unit %s", 'CMDVMGError': "VMG error with command:\n%s\n%s\n%s",
         'CMDVMGWarning': "VMG warning:\n%s"}
    return m
